#+STARTUP: show2levels
#+OPTIONS: num:nil author:nil
* Rust Scripts
** List of scripts
*** relay-mpv

relay a stream to a named pipe with mpv

allows you to stream a video from mpv to a obs studio media source

#+begin_src sh
relay-mpv -i url -s 00:00:00 -e 00:00:00
#+end_src

Run the script with the -h option to show the help.

#+begin_src sh
relay-mpv -h
#+end_src

Help output.

#+begin_example
relay a stream to a named pipe with mpv

Usage: relay-mpv [OPTIONS] -i <INPUT>

Options:
  -i <INPUT>     Input URL (YouTube, etc.)
  -s <START>     Start time (optional)
  -e <END>       End time (optional)
  -h, --help     Print help
  -v, --version  Print version

Example:
 relay-mpv -i 'URL' -s 00:00:00 -e 00:00:10

Dependencies:
 mpv, yt-dlp
#+end_example

*** pinch

sends a link from youtube to mpd using a socket

The socket should be location can be set using the MPD_HOST variable in your shell config

Or using XDG_RUNTIME_DIR directory and /mpd/socket

for instance

#+begin_example
/run/user/1000/mpd/socket
#+end_example

or using the following directory

#+begin_example
~/.config/mpd/socket
#+end_example

#+begin_src sh
pinch -i url
#+end_src

Run the script with the -h option to show the help.

#+begin_src sh
pinch -h
#+end_src

Help output.

#+begin_example
pinch send youtube audio to mpd

Usage: pinch -i <INPUT>

Options:
  -i <INPUT>     Input URL (YouTube, etc.)
  -h, --help     Print help
  -v, --version  Print version

Example:
 pinch -i 'URL'

Dependencies:
 mpd, mpc:
 yt-dlp: https://github.com/yt-dlp/yt-dlp
 deno: https://deno.com/
#+end_example

** Scripts install
*** NixOS install
:PROPERTIES:
:CUSTOM_ID: nixos-install
:END:

**** Install Dependencies

Install dependencies with home-manager by adding the following packages.

[[https://github.com/nix-community/home-manager]]

#+begin_example
mpv
ffmpeg-full
yt-dlp
deno
#+end_example

**** Environment Path Setup
***** create bin directory

Create a bin directory in your home folder to store the scripts.

#+BEGIN_SRC sh
mkdir -p ~/bin
#+END_SRC

***** zsh shell

#+begin_example
~/.zshenv
#+end_example

If you are using zsh add the following code to your ~/.zshenv file

This sets up the PATH for the rust scripts

#+begin_src sh
typeset -U PATH path
path=("$HOME/bin" "$path[@]")
export PATH
#+end_src

Source your ~/.zshenv if you are using the zsh shell

#+BEGIN_SRC sh
source ~/.zshenv
#+END_SRC

***** bash shell

#+begin_example
~/.bashrc
#+end_example

If you are using bash add the following code to your ~/.bashrc

This sets up the PATH for the rust scripts and configures the ffplay video driver.

#+BEGIN_SRC sh
if [ -d "$HOME/bin" ]; then
   PATH="$HOME/bin:$PATH"
fi
#+END_SRC

Source your ~/.bashrc if you are using the bash shell

#+BEGIN_SRC sh
source ~/.bashrc
#+END_SRC

*** Linux install
:PROPERTIES:
:CUSTOM_ID: linux-install
:END:

**** ffmpeg install

Install ffmpeg on debian or ubuntu,
for other linux distros see the documentation for your package manager

#+BEGIN_SRC sh
sudo apt install ffmpeg
#+END_SRC

**** mpv install

Install mpv on debian or ubuntu,
for other linux distros see the documentation for your package manager

#+begin_src sh
sudo apt install mpv
#+end_src

**** yt-dlp install

yt-dlp needed for trim-remote-clip

***** download yt-dlp

#+begin_src sh
curl 'https://github.com/yt-dlp/yt-dlp/releases/download/2025.12.08/yt-dlp' -o ~/bin/yt-dlp 
#+end_src

***** make yt-dlp executable

#+begin_src sh
chmod +x ~/bin/yt-dlp 
#+end_src

yt-dlp upgrade

#+begin_src sh
yt-dlp -U
#+end_src

***** install deno

#+begin_src sh
curl -fsSL https://deno.land/install.sh | sh 
#+end_src

upgrade deno

#+begin_src sh
deno upgrade
#+end_src

**** Environment Path Setup
***** create bin directory

Create a bin directory in your home folder to store the scripts.

#+BEGIN_SRC sh
mkdir -p ~/bin
#+END_SRC

***** zsh shell

#+begin_example
~/.zshenv
#+end_example

If you are using zsh add the following code to your ~/.zshenv file

This sets up the PATH for the rust scripts, yt-dlp, and deno.

#+begin_src sh
typeset -U PATH path
path=("$HOME/bin" "${HOME}/.deno/bin" "$path[@]")
export PATH
#+end_src

Source your ~/.zshenv if you are using the zsh shell

#+BEGIN_SRC sh
source ~/.zshenv
#+END_SRC

***** bash shell

#+begin_example
~/.bashrc
#+end_example

If you are using bash add the following code to your ~/.bashrc

This sets up the PATH for the rust scripts, yt-dlp, and deno.

#+BEGIN_SRC sh
if [ -d "$HOME/bin" ]; then
   PATH="$HOME/bin:$HOME/.deno/bin:$PATH"
fi
#+END_SRC

Source your ~/.bashrc if you are using the bash shell

#+BEGIN_SRC sh
source ~/.bashrc
#+END_SRC

*** Mac install
:PROPERTIES:
:CUSTOM_ID: mac-install
:END:

**** Xcode install

On macOS, you will need to install the development tools and the Rust compiler to build the scripts from source.

Install the Xcode Command Line Tools to provide the necessary compilers,
by running the following command in the terminal.

#+begin_src sh
xcode-select --install
#+end_src

**** Rust install

Install the Rust toolchain using rustup.

#+begin_src sh
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
#+end_src

**** homebrew install

[[https://brew.sh/]]

Install the Homebrew package manager.
Run the following command in the terminal to install homebrew.

#+begin_src sh
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#+end_src

Note: When the installer finishes, look for the "Next steps" section in your terminal.
You must run the commands provided there to add Homebrew to your system PATH.

**** Install Dependencies

Install dependencies with homebrew,
by running the following command in the terminal.

#+begin_src sh
brew install ffmpeg yt-dlp deno mpv
#+end_src

**** Environment Path Setup
***** create bin directory

Create a bin directory in your home folder to store the scripts.

#+BEGIN_SRC sh
mkdir -p ~/bin
#+END_SRC

***** zsh shell

#+begin_example
~/.zshenv
#+end_example

Add the following code to your ~/.zshenv file.
This is the default shell for macOS.

This sets up the PATH for the rust scripts.

#+begin_src sh
typeset -U PATH path
path=("$HOME/bin" "$path[@]")
export PATH
#+end_src

Source the configuration to apply changes.

#+BEGIN_SRC sh
source ~/.zshenv
#+END_SRC

***** bash shell

#+begin_example
~/.bashrc
#+end_example

If you are using bash add the following code to your ~/.bashrc

This sets up the PATH for the rust scripts.

#+BEGIN_SRC sh
if [ -d "$HOME/bin" ]; then
   PATH="$HOME/bin:$PATH"
fi
#+END_SRC

Source your ~/.bashrc if you are using the bash shell

#+BEGIN_SRC sh
source ~/.bashrc
#+END_SRC

**** Compile and Install

Since macOS requires manual compilation,
follow these steps to build the binaries and move them to your bin folder.

***** Clone the git repository

Create a directory to store the git repository in your home directory.

#+begin_src sh
mkdir -p ~/git 
#+end_src

Change into the git directory in your home.

#+begin_src sh
cd ~/git
#+end_src

Run the following command in the terminal to clone the rust-scripts git repository.

#+begin_src sh
git clone https://github.com/NapoleonWils0n/rust-scripts
#+end_src

***** Build the project using Cargo.

Change directory into the rust-scripts git repository.

#+begin_src sh
cd rust-scripts
#+end_src

Build the project with Cargo.

#+begin_src sh
cargo build --release
#+end_src

When you run cargo build --release,
Rust places the binaries in target/release/

Copy the scripts to the bin directory in your home.

#+begin_src sh
cp target/release/* ~/bin/
#+end_src

Note: You may see some non-executable files in the bin folder after this command (like .d files).
This is normal, but you only need the files that match the script names.

*** Freebsd install
:PROPERTIES:
:CUSTOM_ID: freebsd-install
:END:

**** Rust install

Install the required tools and the Rust toolchain using the pkg manager.
Run the following command in the terminal to install Rust.

#+begin_src sh
sudo pkg install rust
#+end_src

**** Install Dependencies

Install dependencies with pkg.

#+BEGIN_SRC sh
sudo pkg install ffmpeg yt-dlp deno mpv
#+END_SRC

**** Environment Path Setup
***** create bin directory

Create a bin directory in your home folder to store the scripts.

#+BEGIN_SRC sh
mkdir -p ~/bin
#+END_SRC

***** sh shell

#+begin_example
~/.profile
#+end_example

For the default shell (sh or tcsh) shell on Freebsd,
edit your shell ~/.profile

add this code to your ~/.profile file.

#+begin_src sh
if [ -d "$HOME/bin" ]; then
    PATH="$HOME/bin:$PATH"
fi
#+end_src

Reload your ~/.profile

#+BEGIN_SRC sh
. ~/.profile
#+END_SRC

***** zsh shell

#+begin_example
~/.zshenv
#+end_example

If you are using zsh add the following code to your ~/.zshenv file

This sets up the PATH for the rust scripts.

#+begin_src sh
typeset -U PATH path
path=("$HOME/bin" "$path[@]")
export PATH
#+end_src

Source your ~/.zshenv if you are using the zsh shell

#+BEGIN_SRC sh
source ~/.zshenv
#+END_SRC

***** bash shell

#+begin_example
~/.bashrc
#+end_example

If you are using bash add the following code to your ~/.bashrc

This sets up the PATH for the rust scripts.

#+BEGIN_SRC sh
if [ -d "$HOME/bin" ]; then
   PATH="$HOME/bin:$PATH"
fi
#+END_SRC

Source your ~/.bashrc if you are using the bash shell

#+BEGIN_SRC sh
source ~/.bashrc
#+END_SRC

**** Compile and Install

Since Freebsd requires manual compilation,
follow these steps to build the binaries and move them to your bin folder.

***** Clone the git repository

Create a directory to store the git repository in your home directory.

#+begin_src sh
mkdir -p ~/git 
#+end_src

Change into the git directory in your home.

#+begin_src sh
cd ~/git
#+end_src

Run the following command in the terminal to clone the rust-scripts git repository.

#+begin_src sh
git clone https://github.com/NapoleonWils0n/rust-scripts
#+end_src

***** Build the project using Cargo.

Change directory into the rust-scripts git repository.

#+begin_src sh
cd rust-scripts
#+end_src

Build the project with Cargo.

#+begin_src sh
cargo build --release
#+end_src

When you run cargo build --release,
Rust places the binaries in target/release/

Copy the scripts to the bin directory in your home.

#+begin_src sh
cp target/release/* ~/bin/
#+end_src

Note: You may see some non-executable files in the bin folder after this command (like .d files).
This is normal, but you only need the files that match the script names.

** NixOS Build and Distribution

This section covers how to compile the scripts for different platforms using Nix.
We use three distinct targets to ensure maximum compatibility.

*** Setup Build Workspace

First, create a structured directory on your Desktop to collect the finished binaries.

Create directories for each target platform

#+begin_src sh
mkdir -p ~/Desktop/build/{nixos,linux}
#+end_src

Optional: Clean existing binaries if doing a fresh release

#+begin_src sh
rm -f ~/Desktop/build/{nixos,linux}/*
#+end_src

*** flake.nix
**** create the project directory

#+begin_src sh
mkdir -p ~/git/projects/rust-scripts/
#+end_src

change directory into the project directory

#+begin_src sh
cd ~/git/projects/rust-scripts/
#+end_src

**** create the flake.nix

#+begin_src sh
vi flake.nix
#+end_src

flake.nix

#+begin_src nix
{
  description = "rust flake";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-unstable";
    naersk.url = "github:nix-community/naersk";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, naersk, rust-overlay, flake-utils }: 
    flake-utils.lib.eachDefaultSystem (system:
    let
      # system is already provided by eachDefaultSystem, so we don't define it here
      overlays = [ (import rust-overlay) ];
      pkgs = import nixpkgs { inherit system overlays; };

      rustToolchain = pkgs.rust-bin.stable.latest.default.override {
        extensions = [ "rust-src" "rust-analyzer" ];
        targets = [ "x86_64-unknown-linux-musl" "x86_64-pc-windows-gnu" ]; 
      };

      naerskLib = (naersk.lib.${system}.override {
        cargo = rustToolchain;
        rustc = rustToolchain;
      });
    in {
      devShells.default = pkgs.mkShell {
        # ADD MINGW TO THE SHELL FOR LINKING
        buildInputs = [ 
          rustToolchain 
          pkgs.pkgsCross.mingwW64.stdenv.cc 
        ];


        # Tell Cargo which linker to use for Windows
        # Add these lines to help the linker find pthreads
        shellHook = ''
          export RUST_SRC_PATH="${rustToolchain}/lib/rustlib/src/rust/library"
          export NIX_CROSS_LDFLAGS="-L${pkgs.pkgsCross.mingwW64.windows.pthreads}/lib"
          export NIX_CROSS_CFLAGS_COMPILE="-I${pkgs.pkgsCross.mingwW64.windows.pthreads}/include"
          export CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER="x86_64-w64-mingw32-gcc"
          export CARGO_TARGET_X86_64_PC_WINDOWS_GNU_RUSTFLAGS="-L ${pkgs.pkgsCross.mingwW64.windows.pthreads}/lib"
        '';
      };

      packages.default = naerskLib.buildPackage {
        src = ./.;
      };
    } 
  ); # This closes eachDefaultSystem
}    # This closes outputs

#+end_src

**** run nix develop

run nix develop which will set up the rust environment

#+begin_src sh
nix develop
#+end_src

**** Cargo Initialization

After entering the Nix development environment for the first time, you must initialize the Rust project structure.

***** Initialize the Project

Run cargo init to generate the necessary Rust configuration files and directory structure within the current folder.

#+begin_src sh
cargo init .
#+end_src

Note: This command creates a Cargo.toml file and a src/ directory with a default main.rs.

***** Staging Project Files

This will automatically create a git repository

Once initialized, you need to track the following essential files in your git repository:

#+begin_example
.gitignore
Cargo.toml
flake.lock
flake.nix
src/
#+end_example

***** Git Setup

Stage all the newly created files:

#+begin_src sh
git add .
#+end_src

Finalize the initialization with an initial commit:

#+begin_src sh
git commit -m 'project init'
#+end_src

**** gitignore

a .gitignore file will be created

#+begin_example
.gitignore
#+end_example

with the following content

#+begin_src sh
/target
#+end_src

we need to edit the .gitignore 

#+begin_src sh
vi .gitignore
#+end_src

and a new line to exclude the results symlink

#+begin_src sh
/target
/result*
#+end_src

check the git status

#+begin_src sh
git status
#+end_src

and then commit the changes

#+begin_src sh
git add .gitignore
#+end_src

and add a commit message

#+begin_src sh
git commit -m "update .gitignore to exclude build results"
#+end_src

*** NixOS build

note you do not need to be inside the nix develop shell to run nix build

run nix build to build the binaries for NixOS

#+begin_src sh
nix build
#+end_src

This will place your binaries in ./result/bin/ instead of target/release/.
Building this way ensures the build is 100% reproducible and isolated from your local system state.
Instead of a simple mv, which might fail if the source is the read-only Nix store, you should copy the binaries.

When you copy a binary out of the Nix store, it keeps its "rpath."
This means it still knows exactly where to find its library dependencies in the nix store, so it will continue to work perfectly.

Create the bin directory in your home if you dont have one

#+begin_src sh
mkdir -p ~/bin
#+end_src

Run this command to copy all 32 binaries at once to the bin directory in your home

#+begin_src sh
cp ./result/bin/* ~/bin/
#+end_src

copy the scripts to the build directory on the desktop for github

#+begin_src sh
cp ./result/bin/* ~/Desktop/build/nixos/
#+end_src

A Note on Updates

Keep in mind that if you change your Rust code and run nix build again, the binaries in ~/bin will not update automatically.
You'll just need to run that cp command again to "deploy" your latest versions.

*** Linux build (static)

To build portable binaries that run on any Linux distribution, we use the musl target.
This statically links all libraries so the binary is self-contained.

You must be inside the nix develop shell to run this command.

#+begin_src sh
nix develop
#+end_src

Build the binaries using the musl target

#+begin_src sh
cargo build --release --target x86_64-unknown-linux-musl
#+end_src

The binaries will be located in target/x86_64-unknown-linux-musl/release/.

list the binaries

#+begin_src sh
ls -l target/x86_64-unknown-linux-musl/release/
#+end_src

How to verify they are truly "Static"
One of the main reasons to use musl is to ensure the binary has no external dependencies.

You can verify this by running the ldd command on one of the new binaries:

#+begin_src sh
ldd target/x86_64-unknown-linux-musl/release/scene-detect-auto
#+end_src

Expected Output: It should say statically linked or not a dynamic executable.

This confirms that a user on Ubuntu, Debian,
or Arch can just download that file and run it immediately (provided they have ffmpeg installed).

Copy the binaries to the build directory on the desktop

#+begin_src sh
fd -t f -d 1 -E "*.*" . target/x86_64-unknown-linux-musl/release/ -x cp {} ~/Desktop/build/linux/
#+end_src

explaination of the fd command

#+begin_example
-t f: Look for files only.

-d 1: Depth 1 (don't go into subfolders like deps or build).

-E "*.*": Exclude any file with a dot in the name (skips .d, .rlib, etc.).

.: The search pattern (matches everything not excluded).

target/.../release/: The directory to search in.

-x cp {} ...: Execute the copy command for every search result.
#+end_example

The ! -name "*.*" logic in standard find can sometimes be finicky depending on the shell, but fd's -E (exclude) flag is very robust.

This will cleanly grab your 32 binaries and ignore all the compiler junk.

*** Create the release
**** rename the build directory on the desktop

#+begin_src sh
cd ~/Desktop
#+end_src

Note: replace v1 with the release number in the examples below.

#+begin_src sh
mv build rust-scripts-build-v1
#+end_src

Change into the rust-scripts-build-v1 directory

#+begin_src sh
cd rust-scripts-build-v1
#+end_src

**** rename the build directories for nixos, linux and windows

linux

#+begin_src sh
mv linux linux-rust-scripts-v1
#+end_src

nixos

#+begin_src sh
mv nixos nixos-rust-scripts-v1
#+end_src

**** remove the rust_scripts file

The rust_scripts file is build from the main.rs which is a list of all the scripts,
and is not needed so we can remove it.

Remove the rust_scripts file from the Linux and NixOS

Linux

#+begin_src sh
rm -i linux-rust-scripts-v1/rust_scripts
#+end_src

NixOS

#+begin_src sh
rm -i nixos-rust-scripts-v1/rust_scripts
#+end_src

**** compress the releases
***** linux

#+begin_src sh
tar -czvf linux-rust-scripts-v1.tar.gz linux-rust-scripts-v1 
#+end_src

***** nixos

#+begin_src sh
tar -czvf nixos-rust-scripts-v1.tar.gz nixos-rust-scripts-v1
#+end_src

**** create release-files directory

#+begin_src sh
mkdir -p release-files-v1
#+end_src

move the tar files and zip into the release-files directory

#+begin_src sh
mv *-rust-scripts-v[0-9]*{.tar.gz} release-files-v1/
#+end_src

**** create checksums for the archives

change directory into the release-files-v1 directory

#+begin_src sh
cd release-files-v1
#+end_src

create the checksums

***** linux 

#+begin_src sh
sha256sum linux-rust-scripts-v1.tar.gz > linux-rust-scripts-v1.tar.gz.sha256
#+end_src

***** nixos

#+begin_src sh
sha256sum nixos-rust-scripts-v1.tar.gz > nixos-rust-scripts-v1.tar.gz.sha256
#+end_src

*** Remove old scripts before rebuilding.

To remove the old scripts before rebuilding

**** nixos

Remove the result symlink which points to the previous Nix store build.

**** linux

Run nix develop to enter the development environment with all necessary dependencies

#+begin_src sh
nix develop
#+end_src

Remove the old compiled binaries and build artifacts (for both Linux and Windows targets) by running cargo clean.

#+begin_src sh
cargo clean
#+end_src
